// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Umbraco.Community.LegacyFeatureConverter.Data;

#nullable disable

namespace Umbraco.Community.LegacyFeatureConverter.Migrations.Sqlite
{
    [DbContext(typeof(LegacyFeatureConverterDbContextSqlite))]
    partial class LegacyFeatureConverterDbContextSqliteModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("AutoBlockList.Models.ConversionHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("CompletedAt");

                    b.Property<string>("ConverterType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("ConverterType");

                    b.Property<int>("FailureCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("FailureCount");

                    b.Property<bool>("IsTestRun")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsTestRun");

                    b.Property<Guid>("PerformingUserKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("PerformingUserKey");

                    b.Property<string>("SelectedDocumentTypes")
                        .HasColumnType("NTEXT")
                        .HasColumnName("SelectedDocumentTypes");

                    b.Property<int>("SkippedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("SkippedCount");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("StartedAt");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Status");

                    b.Property<int>("SuccessCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("SuccessCount");

                    b.Property<string>("Summary")
                        .HasColumnType("NTEXT")
                        .HasColumnName("Summary");

                    b.Property<int>("TotalContentNodes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("TotalContentNodes");

                    b.Property<int>("TotalDataTypes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("TotalDataTypes");

                    b.Property<int>("TotalDocumentTypes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("TotalDocumentTypes");

                    b.HasKey("Id");

                    b.ToTable("LegacyFeatureConverterHistory", (string)null);
                });

            modelBuilder.Entity("AutoBlockList.Models.ConversionLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.Property<Guid>("ConversionHistoryId")
                        .HasColumnType("TEXT")
                        .HasColumnName("ConversionHistoryId");

                    b.Property<string>("Details")
                        .HasColumnType("NTEXT")
                        .HasColumnName("Details");

                    b.Property<string>("ItemKey")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("ItemKey");

                    b.Property<string>("ItemName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("ItemName");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("ItemType");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("Level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("Message");

                    b.Property<string>("StackTrace")
                        .HasColumnType("NTEXT")
                        .HasColumnName("StackTrace");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT")
                        .HasColumnName("Timestamp");

                    b.HasKey("Id");

                    b.HasIndex("ConversionHistoryId")
                        .HasDatabaseName("IX_LegacyFeatureConverterLog_HistoryId");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_LegacyFeatureConverterLog_Timestamp");

                    b.ToTable("LegacyFeatureConverterLog", (string)null);
                });

            modelBuilder.Entity("AutoBlockList.Models.ConversionLogEntry", b =>
                {
                    b.HasOne("AutoBlockList.Models.ConversionHistory", null)
                        .WithMany("LogEntries")
                        .HasForeignKey("ConversionHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AutoBlockList.Models.ConversionHistory", b =>
                {
                    b.Navigation("LogEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
